[project]
name = "blacklite"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.2",
    "sqlite-utils>=3.39",
    "zstandard>=0.25.0",
]
